{% set name = "hstspreload" %}
{% set version = "2020.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0f02fd8f4fd40eb8dd406742c2a2531685dbdb6f7e96f3eb88c80b856de658fe

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - hstspreload

about:
  home: https://hstspreload.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Chromium HSTS Preload list as a Python package and updated daily.
  doc_url: https://hstspreload.org/

extra:
  recipe-maintainers:
    - primozgodec
